// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string TestExtensionString = "05271709-8845-42fb-9d10-621cc8cffc5d";
        public static Guid TestExtension = new Guid(TestExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TestExtensionMainMenu = 0x1000;
        public const int TestExtensionMainMenuGroup1 = 0x1100;
        public const int RunnerWindow = 0x0100;
        public const int ThemeWindow = 0x0101;
        public const int MultiInstanceWindow = 0x0102;
        public const int BuildActiveProjectAsync = 0x0103;
        public const int BuildSolutionAsync = 0x0104;
    }
}