using static EnvDTE.Constants;
namespace Community.VisualStudio.Toolkit
{
    /// <summary>
    /// Provides GUIDs that are used to identify Visual Studio tool windows.
    /// </summary>
    public class WindowGuids
    {
        /// <summary>The Main window.</summary>
        public const string MainWindow = vsWindowKindMainWindow;

        /// <summary>The Document well</summary>
        public const string DocumentWell = "DocumentWell";

        /// <summary>The CallStack window.</summary>
        public const string CallStack = vsWindowKindCallStack;

        /// <summary>The Locals window.</summary>
        public const string Locals = vsWindowKindLocals;

        /// <summary>The Auto window.</summary>
        public const string AutoLocals = vsWindowKindAutoLocals;

        /// <summary>The Watch window.</summary>
        public const string Watch = vsWindowKindWatch;

        /// <summary>The Web Browser window.</summary>
        public const string WebBrowser = vsWindowKindWebBrowser;

        /// <summary>The Properties window.</summary>
        public const string Properties = vsWindowKindProperties;

        /// <summary>The Git Changes window introduced in Visual Studio 2019.</summary>
        public const string GitChanges = "{1C64B9C2-E352-428E-A56D-0ACE190B99A6}";

        /// <summary>The Git Repository window introduced in Visual Studio 2019.</summary>
        public const string GitRepository = "{1C4FEEAA-4718-4AA9-859D-94CE25D182BA}";

        /// <summary>The Error List window.</summary>
        public const string ErrorList = "{D78612C7-9962-4B83-95D9-268046DAD23A}";

        /// <summary>
        /// Provides a list of components that can be added to a project, typically through the Windows Forms designer.
        /// </summary>
        public const string Toolbox = vsext_wk_Toolbox;

        /// <summary>
        /// Provides a list of properties associated with the currently selected file or project in the Solution Explorer.
        /// </summary>
        public const string PropertyBrowser = vsWindowKindProperties;

        /// <summary>
        /// Provides a list of projects and their files in a solution.
        /// </summary>
        public const string SolutionExplorer = vsWindowKindSolutionExplorer;

        /// <summary>Displays any output generated by a build process or a program being debugged.</summary>
        public const string OutputWindow = vsWindowKindOutput;

        /// <summary>Provides an outline of an HTML file.</summary>
        public const string DocOutline = vsWindowKindDocumentOutline;

        /// <summary>Provides a list of user-specified tasks to be accomplished for a project.</summary>
        public const string TaskList = vsWindowKindTaskList;

        /// <summary>Provides a list of servers used for connecting to databases.</summary>
        public const string ServerExplorer = vsWindowKindServerExplorer;

        /// <summary>Provides a list of macros available for use in the Visual Studio shell.</summary>
        public const string MacroExplorer = vsWindowKindMacroExplorer;

        /// <summary>Provides links to help topics based on the current context.</summary>
        public const string ContextWindow = vsWindowKindDynamicHelp;

        /// <summary>Provides a list of all classes in a solution.</summary>
        public const string ClassView = vsWindowKindClassView;

        /// <summary>Provides a list of resources available in a project.</summary>
        public const string ResourceView = vsWindowKindResourceView;

        /// <summary>Provides the ability to search for a symbol.</summary>
        public const string ObjectSearchWindow = vsWindowKindFindSymbol;

        /// <summary>Provides a way to execute commands directly in the Visual Studio shell.</summary>
        public const string CommandWindow = vsWindowKindCommandWindow;

        /// <summary>Provides the results of searching for a symbol.</summary>
        public const string ObjectSearchResultsWindow = vsWindowKindFindSymbolResults;

        /// <summary>Provides a list of components installed on the system.</summary>
        public const string ObjectBrowser = vsWindowKindObjectBrowser;

        /// <summary>For internal use only.</summary>
        public const string BrowserDoc = "{6B8E94B4-0949-4D9C-A81F-C1B9B744185C}";

        /// <summary>Provides the ability to search and replace on the currently opened file.</summary>
        public const string FindReplace =
#if VS14 || VS15
            vsWindowKindFindReplace
#else
            "{6324226F-61B6-4F28-92EE-18D4B5FE1E48}"
#endif
            ;

        /// <summary>Provides the ability to search files for a string.</summary>
        public const string FindAdvanced = "{E830EC50-C2B5-11D2-9375-0080C747D9A0}";

        /// <summary>Provides a list of the search results.</summary>
        public const string FindResults1 = vsWindowKindFindResults1;

        /// <summary>Provides a second list of search results.</summary>
        public const string FindResults2 = vsWindowKindFindResults2;

        /// <summary>Provides a command prompt for PowerShell.</summary>
        public const string DeveloperPowerShell = "{D212F56B-C48A-434C-A121-1C5D80B59B9F}";
    }
}
