// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSSDK.TestExtension.5a9a059d-5738-41dc-9075-250890b4ef6f";
        public const string Name = "VSSDK.TestExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
