// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string TestExtensionString = "05271709-8845-42fb-9d10-621cc8cffc5d";
        public static Guid TestExtension = new Guid(TestExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TestExtensionMainMenu = 0x1000;
        public const int TestExtensionSolutionExplorerMenu = 0x1001;
        public const int TestExtensionEditProjectFileMenu = 0x1002;
        public const int TestExtensionMainMenuGroup1 = 0x1100;
        public const int TestExtensionSolutionExplorerGroup = 0x1101;
        public const int TestExtensionEditProjectFileGroup = 0x1102;
        public const int RunnerWindowToolbarGroup = 0x1103;
        public const int RunnerWindow = 0x0100;
        public const int ThemeWindow = 0x0101;
        public const int MultiInstanceWindow = 0x0102;
        public const int BuildActiveProjectAsync = 0x0103;
        public const int BuildSolutionAsync = 0x0104;
        public const int VsixManifestSolutionExplorerFilter = 0x0105;
        public const int ToggleVsixManifestFilter = 0x0106;
        public const int SelectCurrentProject = 0x0107;
        public const int EditSelectedItemLabel = 0x0108;
        public const int ExpandSelectedItems = 0x0109;
        public const int CollapseSelectedItems = 0x0110;
        public const int ListReferences = 0x0111;
        public const int LoadSelectedProject = 0x0112;
        public const int UnloadSelectedProject = 0x0113;
        public const int SendMessageToRunnerWindow = 0x0114;
        public const int EditProjectFile = 0x2001;
        public const int RunnerWindowToolbar = 0x0BB8;
    }
}